---
title: "backend"
author: "Zhiwei Song"
date: "1/29/2022"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, message=FALSE, warning=FALSE}
library("readxl")
library("dplyr")
library("tidyr")
library("tidyverse")
library("knitr")
library("ggplot2")
theme_set(theme_bw())
library("sf")
library("rnaturalearth")
library("rnaturalearthdata")
library("lubridate")
library(reshape2)
```

```{r message=FALSE, warning=FALSE}
cells <- c("breast_variant_human_mammary_epithelial_cells_vhmec", "cd19", "cd34_primary_cells", "cd3_primary_cells", 
    "cd4_primary_cells", "cd56_primary_cells", "cd8_primary_cells", "fetal_adrenal_gland", "fetal_heart", "fetal_intestine_large", 
    "fetal_intestine_small", "fetal_kidney", "fetal_lung", "fetal_muscle", "fetal_muscle_arm", "fetal_muscle_back", 
    "fetal_muscle_leg", "fetal_muscle_lower_limb", "fetal_muscle_trunk", "fetal_ovary", "fetal_renal_cortex", 
    "fetal_renal_pelvis", "fetal_skin", "fetal_spinal_cord", "fetal_stomach", "fetal_testes", "fetal_thymus", "fibroblast", 
    "fibroblasts_fetal_skin_abdomen", "fibroblasts_fetal_skin_back", "fibroblasts_fetal_skin_biceps_left", "fibroblasts_fetal_skin_biceps_right", 
    "fibroblasts_fetal_skin_quadriceps_left", "fibroblasts_fetal_skin_quadriceps_right", "fibroblasts_fetal_skin_scalp", 
    "fibroblasts_fetal_skin_upper_back", "gastric_mucosa", "h1_bmp4_derived_mesendoderm_cultured_cells", "h1_bmp4_derived_trophoblast_cultured_cells", 
    "h1_cells", "h1_derived_mesenchymal_stem_cells", "h1_derived_neuronal_progenitor_cultured_cells", "h9_cells", 
    "imr90_fetal_lung_fibroblasts_cell_line", "keratinocyte", "melanocyte", "ovary", "pancreas", "placenta", 
    "psoas_muscle", "small_bowel_mucosa", "testes")


my_data <- read_excel("modularity_index.xlsx", col_names = FALSE)
```
```{r}
print(as.integer(unlist(my_data[((1 - 1)*12+1 + 1):((1 - 1)*12+1 + 10), 2])))
```



```{r message=FALSE, warning=FALSE}
for (rownum in 1:55){
  assign(as.character(my_data[(rownum - 1)*12+1,2]), as.integer(unlist(my_data[((rownum-1)*12+1 + 1):((rownum - 1)*12+1 + 10), 2])))
  for (i in 3:ncol(my_data)){
    assign(as.character(my_data[(rownum - 1)*12+1,i]), as.numeric(unlist(my_data[((rownum-1)*12+1 + 1):((rownum - 1)*12+1 + 10), i])))
  }
  
  df <- data.frame(cluster_num, spectral_clustering, node2vec_64d_p1_q1, node2vec_64d_p1_q0.5, node2vec_64d_p1_q2,
    node2vec_128d_p1_q1, node2vec_128d_p1_q0.5, node2vec_128d_p1_q2, node2vec_256d_p1_q1, node2vec_256d_p1_q0.5,
    node2vec_256d_p1_q2, DeepWalk_64d, DeepWalk_128d, DeepWalk_256d, Ohmnet_15_64d,
    Ohmnet_15_128d, Ohmnet_15_256d)
  
  assign(as.character(my_data[(rownum - 1)*12+1,1]), df)
}
```

```{r}
dfm <- melt(cd19[,c('cluster_num','node2vec_128d_p1_q1','node2vec_128d_p1_q0.5','node2vec_128d_p1_q2')],id.vars = 1)
ggplot(dfm, aes(x=cluster_num, y = value)) + 
  geom_bar(aes(fill = variable),stat = "identity",position = "dodge") +
  labs(y= "Modularity Value", x= "# of Clusters") +
  scale_x_continuous(breaks=seq(0, 100, 10)) +
  ggtitle("cd19")
```

```{r}
dfm_1 <- melt(cd19[,c('cluster_num','node2vec_128d_p1_q1','node2vec_128d_p1_q0.5','node2vec_128d_p1_q2')],id.vars = 1)
ggplot(dfm_1, aes(x=cluster_num, y = value)) + 
  geom_line(aes(color = variable, linetype = variable)) +
  scale_color_manual(values = c("darkred", "steelblue", "darkgreen")) +
  scale_linetype_manual(values=c("solid", "solid", "solid")) +
  labs(y= "Modularity Value", x= "# of Clusters") +
  scale_x_continuous(breaks=seq(0, 100, 10)) +
  ggtitle("cd19")
```


