function Get_Unweighted_Adjmat()
    cells = {'breast_variant_human_mammary_epithelial_cells_vhmec', 'cd14_primary_cells', 'cd19', 'cd34_primary_cells', 'cd3_primary_cells', 'cd4_primary_cells', ...
    'cd56_primary_cells', 'cd8_primary_cells', 'fetal_adrenal_gland', 'fetal_brain', 'fetal_heart', 'fetal_intestine_large', ...
    'fetal_intestine_small', 'fetal_kidney', 'fetal_lung', 'fetal_muscle', 'fetal_muscle_arm', ...
    'fetal_muscle_back', 'fetal_muscle_leg', 'fetal_muscle_lower_limb', 'fetal_muscle_trunk', 'fetal_ovary', ...
    'fetal_renal_cortex', 'fetal_renal_pelvis', 'fetal_skin', 'fetal_spinal_cord', 'fetal_stomach', ...
    'fetal_testes', 'fetal_thymus', 'fibroblast', 'fibroblasts_fetal_skin_abdomen', 'fibroblasts_fetal_skin_back', ...
    'fibroblasts_fetal_skin_biceps_left', 'fibroblasts_fetal_skin_biceps_right', 'fibroblasts_fetal_skin_quadriceps_left', 'fibroblasts_fetal_skin_quadriceps_right', ...
    'fibroblasts_fetal_skin_scalp', ...
    'fibroblasts_fetal_skin_upper_back', 'gastric_mucosa', 'heart', 'h1_bmp4_derived_mesendoderm_cultured_cells', 'h1_bmp4_derived_trophoblast_cultured_cells', 'h1_cells', ...
    'h1_derived_mesenchymal_stem_cells', 'h1_derived_neuronal_progenitor_cultured_cells', 'h9_cells', 'imr90_fetal_lung_fibroblasts_cell_line', 'keratinocyte', ...
    'melanocyte', 'ovary', 'pancreas', 'placenta', 'psoas_muscle', ...
    'small_bowel_mucosa', 'testes'};
    
    for i = 1:length(cells)
        cell = cells{i};
        fprintf('%s\n', cell);
        adjmat=importdata(sprintf('/mnt/dv/wid/projects3/Roy-enhancer-promoter/Zhiwei_Work/RoadMap_Networks_Cad/Data/adj_matrix/%s.txt',cell));
        nodeNames=readtable(sprintf('/mnt/dv/wid/projects3/Roy-enhancer-promoter/Zhiwei_Work/RoadMap_Networks_Cad/Data/adj_matrix/%s_nodeNames.txt',cell));
        
        mat_len = length(adjmat)
        average_weight = sum(sum(adjmat)) / (mat_len*mat_len);
        
        adjmat_unweighted = adjmat >= average_weight;      
        logical_index = sum(adjmat_unweighted) ~= 0;
        
        nodeNames_unweighted = nodeNames(logical_index, :);
        adjmat_unweighted = adjmat_unweighted(logical_index, logical_index);
        
        writematrix(adjmat_unweighted, sprintf('/mnt/dv/wid/projects3/Roy-enhancer-promoter/Zhiwei_Work/RoadMap_Networks_Cad/Data/adj_matrix/%s_no_weight.txt',cell), 'Delimiter', ' ');
        writetable(nodeNames_unweighted, sprintf('/mnt/dv/wid/projects3/Roy-enhancer-promoter/Zhiwei_Work/RoadMap_Networks_Cad/Data/adj_matrix/%s_nodeNames_no_weight.txt',cell), 'Delimiter', '\t', 'WriteVariableNames',0)
    end
end